### ISSUE TITLE
Where is tidy/infant_hiv.csv?

### ISSUE THREAD

**Issue by rmdickson** [gvwilson/tidynomicon#12]
> #> data <- read_csv('tidy/infant_hiv.csv')
> Error: 'tidy/infant_hiv.csv' does not exist in current working directory ('C:/Users/rdickson').

This is after a successful install.packages("tidyverse"); library(tidyverse); on a Windows 10 platform.  I can't find a file of that name anywhere on my hard drive.  Is infant_hiv.csv part of the tidyverse package, or should there be explicit instructions on how to obtain it?

**Comment by gvwilson** [comment]
Will be fixed by #19.
