### ISSUE TITLE
Domain expired?

### ISSUE THREAD

**Issue by firasm** [gvwilson/tidynomicon#53]
Hello @gvwilson - just wanted to point out that it looks like your domain has expired. This is a fantastic resource and I was about to recommend this to my students. Hopefully a backup version can be deployed soon?

I get this message when I try to visit https://tidynomicon.tech.

<img width="1033" alt="Screen Shot 2020-09-22 at 9 28 31 PM" src="https://user-images.githubusercontent.com/2507459/93966853-95a7ca80-fd1a-11ea-8546-edef82beb628.png">

**Comment by gvwilson** [comment]
Hi @firasm - I let the domain expire because the project wasn't getting enough interest or traffic to keep maintaining. I'll leave everything in the GitHub repo, and I'll take out the CNAME so it can be viewed at http://gvwilson.github.io/tidynomicon - thanks for the reminder.

**Comment by firasm** [comment]
Sounds good! 

That's great, will update links on our site :-)

I'm surprised this wasn't getting enough interest or traffic! It's how I learned R last summer!
